### ISSUE TITLE
Does this package works well withe Nuxt Content?

### ISSUE THREAD

**Issue by Barbapapazes** [harlan-zw/nuxt-seo-kit#1]
### Details

Will a `useHead` written in my `app.vue` file overwrite yours?

**Comment by harlan-zw** [comment]
It should play nicely with nuxt/content, though it depends on where you put the SeoKit component.

You can see how I'm using it on my personal site https://github.com/harlan-zw/harlanzw.com/blob/main/app.vue

In terms of overriding the data with your own useHead, it would again depend on where you have the SeoKit component. For example, if you have SeoKit in app.vue, then any pages will override the data

**Comment by Barbapapazes** [comment]
Thanks for your answer. I'm playing with this module which is clearly a must have.

**Comment by nicolas-bastien** [comment]
Hi @harlan-zw,

I try to integrate it wth nuxt content but breadcrumd is not generated.
I saw you don't have breadcrum on your website to.

After digging, I think that composables/breacrumbs.ts is only watching routes from router but on content pages the route is only the slug catch all.
I tried to pass by the query content to fetch content but I'm stacked with the async/await problem.

> const contents = await queryContent().only(['title', 'navigation', '_path']).find()

but in your computed contents is alway null when I want to use it.
I'm sure I not good enough is JS to make a clean code but I can help testing if your want.

Nuxt content have a navigation feature which allow to set a navigation.title in meta, I think it would be nice to try to use it as a fallback of 'meta?.breadcrumbTitle'.

**Comment by nicolas-bastien** [comment]
Hi @harlan-zw,

I managed to make the breadcrumb appear async in development but it's not working when generating with yarn generate.

Here is my code in breadcrumb.ts (I noticed I remove the routing, I was trying to make it work for content first) : 

```js
export async function useBreadcrumbs() {
  const router = useRouter()
  const route = router.currentRoute.value
  const contents = await queryContent().only(['title', 'navigation', '_path']).find()
  const breadcrumbRoutes = getBreadcrumbs(route.path).reverse()
  const breadcrumbs = computedAsync(
    async () => {
      let toReturn = []
      for (let i = 0; i < breadcrumbRoutes.length; i++) {
        for await (const content of contents) {
          if (content._path === breadcrumbRoutes[i]) {
            let title = content?.breadcrumbTitle || content?.navigation?.title || content?.title || titleCase(breadcrumbRoutes[i].replaceAll('/', ' ').trim())
            toReturn[i] = {
              path: breadcrumbRoutes[i],
              schema: {
                name: title,
                item: resolveAbsoluteInternalLink(breadcrumbRoutes[i]),
              },
              to: resolveTrailingSlash(breadcrumbRoutes[i]),
              title
            }
            continue
          }
        }
      }
      return toReturn
    },
    []
  )
console.log(breadcrumbs)
  return breadcrumbs
}

```

I don't know how to handle the async during generation process.
Do you have an idea ?

Thanks a lot
Nicolas
