### ISSUE TITLE
sitemap.xml valid but google cant fetch it

### ISSUE THREAD

**Issue by impronta48** [harlan-zw/nuxt-seo-kit#101]
### Describe the bug

I've generated a static site using Nuxt3.
I get a sitemap, which looks valid (and is validated by https://www.xml-sitemaps.com/validate-xml-sitemap.html

https://mobilitysquare.eu/sitemap.xml

The website is up and running, google lightspeed finds it ok...
But: Google Search Console says "Sitemap can't be retrieved"

Any idea about what I'm doing wrong?
Thanks

### System / Nuxt Info

```Shell
Nuxt3

  "devDependencies": {
    "@nuxt/content": "^2.7.2",
    "@nuxt/devtools": "latest",
    "@nuxt/image": "1.0.0-rc.1",
    "@types/node": "^18.17.12",
    "nuxt": "^3.7.0",
    "sass": "~1.64.2"
  },
  "dependencies": {
    "@dargmuesli/nuxt-cookie-control": "^6.4.1",
    "@popperjs/core": "^2.11.8",
    "@productdevbook/chatwoot": "^1.2.0",
    "aos": "^2.3.4",
    "bootstrap": "^5.3.1",
    "glightbox": "^3.2.0",
    "nuxt-seo-kit": "^1.3.9",
    "nuxt-swiper": "^1.2.2",
    "vue-slick-carousel": "^1.0.6"
  },
```

**Comment by harlan-zw** [comment]
Should solve itself, see https://github.com/harlan-zw/nuxt-simple-sitemap/issues/125

**Comment by harlan-zw** [comment]
Any update?
