### ISSUE TITLE
[v2] Why is `sitemap.xml` not generated by default?

### ISSUE THREAD

**Issue by Sun-ZhenXing** [harlan-zw/nuxt-seo-kit#107]
### Details

I don't like prebuild, so I tried v2.

I tested **beta15** & **beta30,** there is no build files that looks like v1. Do I need to wait for the official version?

**Comment by harlan-zw** [comment]
Hi @Sun-ZhenXing 

The v1 forces prerendering to be enabled. 

You can replicate the same behavior by doing this:

```ts
  nitro: {
    prerender: {
      crawlLinks: true,
      routes: [
        '/',
      ],
    },
  },
```

However you don't need this files pre-built, they will be generated at runtime.

**Comment by Sun-ZhenXing** [comment]
Thank you. I am looking forward to the official version with great anticipation.
