### ISSUE TITLE
Ensure inferred og:image has absolute URL

### ISSUE THREAD

**Issue by Ben-VP** [harlan-zw/nuxt-seo-kit#11]
### Describe the bug

When pointing to the image, the absolute URL doesn't get added. This results in some services not picking up the og:image. For example Whatsapp and iMessage will pickup the og:image but Twitter will not.

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 37.98 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.9.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.1 - /opt/homebrew/bin/npm
  Browsers:
    Firefox Developer Edition: 109.0
    Safari: 16.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by harlan-zw** [comment]
Thanks @Ben-VP 

Available in 0.4.15
