### ISSUE TITLE
How to disable link-checker error on broken links?

### ISSUE THREAD

**Issue by gmsa** [harlan-zw/nuxt-seo-kit#12]
### Details

I have some links that refer to relative urls that will work when the site is deployed (pages on a subfolder generated by another tool), but can't disable the broken link checker.

I tried the 3 configs below, none seems to work: 

```ts
  runtimeConfig: {
    public: {
      failOn404: false,
    }
  },

```

```ts
  runtimeConfig: {
      failOn404: false,
    }
  },
```

```ts
  runtimeConfig: {
    linkChecker: {
      failOn404: false,
    }
  },

```

**Comment by harlan-zw** [comment]
Hey @gmsa 

You can use the `linkChecker.failOn404` option within nuxt.config.ts.

```ts
export default defineNuxtConfig({
  linkChecker: {
    failOn404: false,
  },
})
```

I've also just added an `exclude` option where you can safelist any URL patterns that you don't want to throw an error. You'd need to manually update `nuxt-link-checker` to 0.3.0 though.

```ts
export default defineNuxtConfig({
  linkChecker: {
    exclude: [
      '/admin/**'
    ],
  },
})
```

**Comment by gmsa** [comment]
Awesome! Thank you for the quick response and new release!
