### ISSUE TITLE
 < SBreadcrumb / > Not using "breadcrumbTitle" or "title"

### ISSUE THREAD

**Issue by albericobenhur** [harlan-zw/nuxt-seo-kit#120]
### Describe the bug

According to the documentation, breadcrumb proposes to use the "breadcrumbTitle" or the title informed in the meta, however it is ignoring this information and using only the path name

### Reproduction

while using < Breadcrumb />

### System / Nuxt Info

```Shell
Nuxt 3.7.4 with Nitro 2.6.3
```

**Comment by hermesalvesbr** [comment]
https://github.com/harlan-zw/nuxt-seo-kit/releases/tag/v2.0.0-beta.39

**Comment by harlan-zw** [comment]
Thanks :) Please let me know if you have any issues with this version. Sorry that it has some breaking changes.
