### ISSUE TITLE
Import error from nuxt-simple-robots

### ISSUE THREAD

**Issue by Barbapapazes** [harlan-zw/nuxt-seo-kit#13]
### Describe the bug

When I start the project, here my console:

```
Nuxi 3.0.0                                                                                                                                        10:05:56
Nuxt 3.0.0 with Nitro 1.0.0                                                                                                                       10:05:56
                                                                                                                                                  10:05:57
  > Local:    http://localhost:3000/
  > Network:  http://192.168.6.3:3000/

i Using Tailwind CSS from ~/assets/css/tailwind.css                                                                              nuxt:tailwindcss 10:05:58
                                                                                                                                                  10:05:59
SEO Kit v0.4.15 • All-in-one SEO by @harlan_zw                                                                                                    10:05:59
  └─ 💖  Like this package? Consider sponsoring me on GitHub https://github.com/sponsors/harlan-zw                                                10:05:59
                                                                                                                                                  10:05:59
i Tailwind Viewer: http://localhost:3000/_tailwind/                                                                              nuxt:tailwindcss 10:06:04
i Vite client warmed up in 13708ms                                                                                                                10:06:24

 ERROR                                                                                                                                      nitro 10:06:24

1: import { defineEventHandler, setHeader } from "h3";
2: import { disallow, indexable, sitemap } from "#nuxt-simple-robots/config";
            ^
3: const asArray = (v) => Array.isArray(v) ? v : [v];
4: export default defineEventHandler(async (event) => {

√ Nitro built in 2673 ms                                                                                                                    nitro 10:06:24
(node:2656) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time                                  10:06:26
(Use `node --trace-warnings ...` to show where the warning was created)
```

There is an import issue with `"nuxt-seo-kit": "^0.4.15",`

### System Info

```Shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 2.69 GB / 15.69 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.3.1 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (109.0.1518.61), ChromiumDev (111.0.1619.2)
    Internet Explorer: 11.0.22000.120
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Barbapapazes** [comment]
I'm not completely sure this issue come from this package..

**Comment by Barbapapazes** [comment]
removing extends from this package this fix the issue.

**Comment by Ben-VP** [comment]
I'd recommend deleting your `node_modules` folder and running `yarn install` & then `yarn dev`.

**Comment by Barbapapazes** [comment]
Will try

**Comment by Barbapapazes** [comment]
not, nothing change. the error is still present.

![image](https://user-images.githubusercontent.com/45267552/214269100-71efc13c-7e65-4e19-aed7-74e168b56147.png)

**Comment by Barbapapazes** [comment]
My CD fail because of this

https://app.netlify.com/sites/le-classement/deploys/63cfb3bfd373c6000889fcd8

**Comment by Barbapapazes** [comment]
Ok, I got the full stack trace

```[error] [nitro]
11:34:05 AM: 1: import { defineEventHandler, setHeader } from "h3";
11:34:05 AM: 2: import { disallow, indexable, sitemap } from "#nuxt-simple-robots/config";
11:34:05 AM:             ^
11:34:05 AM: 3: const asArray = (v) => Array.isArray(v) ? v : [v];
11:34:05 AM: 4: export default defineEventHandler(async (event) => {
11:34:05 AM: [error] 'disallow' is not exported by virtual:#nuxt-simple-robots/config, imported by node_modules/nuxt-simple-robots/dist/runtime/server/robots-route.mjs
```

Issue is from nuxt-simple-robots

**Comment by Ben-VP** [comment]
How are you serving your site? I notice you are using yarn build, it should be `nuxi generate` if you are static hosting your site.

https://nuxt.com/docs/getting-started/deployment#static-hosting

Can you share your nuxt.config.ts? I'm running Nuxt 3 with Nuxt-SEO-Kit v4.15 and I'm not experiencing these issues.

**Comment by harlan-zw** [comment]
Hey @Barbapapazes 

Sorry about that, looks like a bug I introduced in `nuxt-simple-robots` earlier.

You have two options in fixing it:
1. manually add `nuxt-simple-robots@0.1.10` as a dependency
2. delete lock file / node_modules and re-install

**Comment by Barbapapazes** [comment]
Okk, will try it!

and @Ben-VP, here my project: https://github.com/Barbapapazes/le-classement.fr/pull/159 (I've got this issue while working on this PR). On I know for `nuxi generate` but I've some issue with active class from router.

**Comment by Barbapapazes** [comment]
Perfect, it works!

fix in https://github.com/harlan-zw/nuxt-simple-robots/commit/2a56aabc106cd22916de30fd399055f3be261dcb
