### ISSUE TITLE
Title Template not working

### ISSUE THREAD

**Issue by JMKelley** [harlan-zw/nuxt-seo-kit#132]
### Describe the bug

Adding the following to nuxt.config.js doesn't seem to change the title seperator.

```
  app: {
    head: {
      templateParams: {
        separator: '•'
      }
    }
  },
```

**Comment by harlan-zw** [comment]
Thanks for the issue, seems like a bug in the [nuxt-seo-experiments](https://github.com/harlan-zw/nuxt-seo-experiments) package.

I've pushed up a fix in 3.1.7.
