### ISSUE TITLE
OG Image generation 

### ISSUE THREAD

**Issue by cannon86** [harlan-zw/nuxt-seo-kit#138]
### Details

Not sure if it's a Nuxt 3.81 issue or Nuxt-seo-kit works with it. When ever I use yarn generate it keeps getting stuck at the end I have to cancel my deploy. Whether I try it on my personal computer or when using Netlify in the image I presented it gets stuck at the bottom. Waited for even 5 to 10 mins to see if it would deploy nothing happens. I have to cancel it every time. Once I remove the OGImageScreenshot component. Yarn generate works just fine and I am able to deploy

![image](https://github.com/harlan-zw/nuxt-seo-kit/assets/107595955/7bce9d08-366c-4fb1-839b-22d15d35b479)

**Comment by harlan-zw** [comment]
Hi, please use the latest version of nuxt-og-image / @nuxtseo/module and this should be resolved.

The issue is that the chromium process isn't being removed properly so the application can't exit.
