### ISSUE TITLE
type issue on  "@nuxtseo/module": "^2.0.0-beta.44",

### ISSUE THREAD

**Issue by jpengelbrecht** [harlan-zw/nuxt-seo-kit#139]
### Describe the bug

![image](https://github.com/harlan-zw/nuxt-seo-kit/assets/93583336/ef9eec09-554d-4117-90b6-6b15e7dd9601)

seems to be used by the og image component

_No response_

------------------------------
- Operating System: Darwin
- Node Version:     v18.10.0
- Nuxt Version:     3.8.1
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  npm@8.19.2
- Builder:          -
- User Config:      modules, site, css, turnstile, sitemap, robots, ogImage, schemaOrg, linkChecker, head, routeRules, typescript, sourcemap, devServer, htmlValidator, image, runtimeConfig, nitro, appConfig, ignore, hooks, vite
- Runtime Modules:  @pinia/nuxt@0.4.11, @nuxt/content@2.7.2, @vueuse/motion/nuxt@2.0.0, nuxt-calendly@0.1.14, vue3-carousel-nuxt@1.1.0, @nuxtjs/turnstile@0.6.3, @nuxtjs/tailwindcss@6.8.0, @nuxtseo/module@2.0.0-beta.44, @nuxt/image@1.0.0
- Build Modules:    -
------------------------------

_No response_

**Comment by harlan-zw** [comment]
The module doesn't use strict dependency versions so you could have fixed this by removing your lock file + node_modules and re-installing.

I've bumped the dependencies either way though so should be fixed in latest version.
