### ISSUE TITLE
Duplicated imports "useSeoMeta", the one from "#head" has been ignored

### ISSUE THREAD

**Issue by kaname-png** [harlan-zw/nuxt-seo-kit#14]
### Describe the bug

I have upgraded to nuxt v3.1.0 and now I get that warning in the console.

![image](https://user-images.githubusercontent.com/56084970/214364500-4583550b-4e71-45ac-a741-26ddd6e19262.png)

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (4) x64 AMD Ryzen 3 3200G with Radeon Vega Graphics    
    Memory: 5.82 GB / 13.94 GB
  Binaries:
    Node: 19.3.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.3.0 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by harlan-zw** [comment]
Hi, please upgrade to 1.0.1 :)
