### ISSUE TITLE
OG image needs nuxt devtools to preview,  however nuxt devtools breaks on newest nuxt seo kit version 

### ISSUE THREAD

**Issue by jpengelbrecht** [harlan-zw/nuxt-seo-kit#143]
### Describe the bug

![image](https://github.com/harlan-zw/nuxt-seo-kit/assets/93583336/a77a6698-6235-497f-adb2-14e5f43997b4)

### Reproduction

https://github.com/jpengelbrecht/nuxt-seo-route-rules-issue/blob/main/nuxt.config.ts

### System / Nuxt Info

```Shell
------------------------------
- Operating System: Darwin
- Node Version:     v18.10.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  pnpm@8.11.0
- Builder:          -
- User Config:      modules, site, routeRules, typescript, sourcemap, devServer, devtools
- Runtime Modules:  @nuxtseo/module@2.0.0-beta.50
- Build Modules:    -
------------------------------
```

**Comment by harlan-zw** [comment]
Hi, I've bumped the Nuxt DevTools Kit version in `v3.0.0-rc.10`, can you see if it works any better for you?

**Comment by jpengelbrecht** [comment]
Yo dude,   gave it a quick whack and it seems that its still not working with the rc.10 version ￼

**Comment by harlan-zw** [comment]
hmm strange, definitely seems to be an upstream issue

**Comment by harlan-zw** [comment]
Is this still an issue with Nuxt 3.9.0 and latest beta version?

**Comment by jpengelbrecht** [comment]
na its fixed, thanks dude
