### ISSUE TITLE
The documentation for redirectToCanonicalSiteUrl varies from the module's default settings.

### ISSUE THREAD

**Issue by maartenvanhunsel** [harlan-zw/nuxt-seo-kit#146]
### Details

When discovering the redirectToCanonicalSiteUrl configuration it looks like there is a difference between the documentation and actual behavior.

See commit: https://github.com/harlan-zw/nuxt-seo-kit/commit/f038733aae3e3078a46000e790270e619da6fdfe
See docs: https://nuxtseo.com/nuxt-seo/api/config#redirecttocanonicalsiteurl

**Comment by harlan-zw** [comment]
Thanks :)
