### ISSUE TITLE
nuxt/tailwindcss doesn't work properly when nuxt-seo-kit is used.

### ISSUE THREAD

**Issue by mukundshah** [harlan-zw/nuxt-seo-kit#17]
### Describe the bug

As soon as I added `nuxt-seo-kit` to `extends` list, the css weny hay wire. Only some/few of classes were being resolved.

The issue resolved after I removed `nuxt-seo-kit`.

### Reproduction

setup a project with nuxt/tailwind and nuxt-seo-kit

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 10.14 GB / 31.92 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by harlan-zw** [comment]
Can you confirm if this is still an issue?

**Comment by mukundshah** [comment]
Waiting on the nuxt-modules/tailwindcss#602

**Comment by harlan-zw** [comment]
Upstream seems to be fixed so going to close this
