### ISSUE TITLE
How to remove the automatic prefix in the page title

### ISSUE THREAD

**Issue by kaname-png** [harlan-zw/nuxt-seo-kit#18]
### Details

I am currently visiting the `domain.com/es` page, and that because I am using nuxt-i18n, but the page title appears with the domain path prefix, how can I disable this behavior?

Example:
![image](https://user-images.githubusercontent.com/56084970/214617797-7af85421-fe2d-44f6-82e8-7e71cab4ebdc.png)

**Comment by harlan-zw** [comment]
Hey @kaname-png 

Thanks for the issue. By default it tries to set a page title if there isn't one set for non-root pages. 

To get around this you can set the title manually to null

```ts
useHead({
  title: null,
})
```

This will also be addressed one i18n is properly supported, you can track that here: https://github.com/harlan-zw/nuxt-seo-kit/issues/4
