### ISSUE TITLE
500 Cannot add property objectMode, object is not extensible

### ISSUE THREAD

**Issue by reslear** [harlan-zw/nuxt-seo-kit#19]
### Describe the bug

hi @harlan-zw thx for super module :)
i'm first using this module, and don't understand how to prevent this error after routing to 
http://localhost:3000/sitemap.preview.xml
i see error: 
 
<img width="705" alt="Screenshot 2023-01-27 at 19 30 13" src="https://user-images.githubusercontent.com/12596485/215166305-94cb707a-511e-4ff2-8732-3f4226267153.png">

<img width="769" alt="Screenshot 2023-01-27 at 19 24 32" src="https://user-images.githubusercontent.com/12596485/215165148-b25ed277-7c3a-434f-be9e-7f85f4cf01dd.png">
<img width="569" alt="Screenshot 2023-01-27 at 19 25 37" src="https://user-images.githubusercontent.com/12596485/215165261-070db6a4-ba04-4c05-bd36-9a47376b2ad6.png">
<img width="562" alt="Screenshot 2023-01-27 at 19 25 59" src="https://user-images.githubusercontent.com/12596485/215165311-1879bee4-144e-4c4b-91b2-c9007c0a73e9.png">

my config 

```ts
// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  extends: ['nuxt-seo-kit'],
  modules: ['nuxt-windicss'],
  css: [
    'virtual:windi.css',
    'virtual:windi-devtools',
    '~/styles/fonts.css',
    '~/styles/main.css',
  ],
  windicss: {
    analyze: true,
  },
  nitro: {
    prerender: {
      routes: ['/'],
    },
  },

  hooks: {
    'sitemap:generate': (ctx) => {
      ctx.urls.push({
        url: '/',
      })
    },
  },
  build: {
    transpile: ['swiper'],
  },
  app: {
    head: {
      htmlAttrs: {
        lang: 'en',
      },
      viewport: 'width=device-width, initial-scale=1, maximum-scale=1',
      titleTemplate: '%s - site',
    },
  },
  runtimeConfig: {
    public: {
      siteUrl: 'https://app.net',
      siteName: 'Network',
      siteDescription:
        'desc',
      language: 'en-US',
      titleSeparator: ' - ',
    },
  },
})
```

its my syntax error or bug?

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M2
    Memory: 436.11 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/Library/Caches/fnm_multishells/1396_1674844241910/bin/node
    npm: 8.19.2 - ~/Library/Caches/fnm_multishells/1396_1674844241910/bin/npm
  Browsers:
    Brave Browser: 109.1.47.186
    Chrome: 109.0.5414.119
    Firefox: 107.0.1
    Safari: 16.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by harlan-zw** [comment]
Hey @reslear, thanks for the detailed issue!

I've pushed up a fix in Nuxt SEO Kit v1.1.4. 

Let me know if you have any issues with it :)
