### ISSUE TITLE
Title is not removed when null

### ISSUE THREAD

**Issue by Barbapapazes** [harlan-zw/nuxt-seo-kit#2]
### Describe the bug

When page title is not defined, it is not remove from page title.

Eg using the reproduction URL:

- Check page title (everything is ok, juste sitename)
- Navigate to a page using the header
- Return to home using le logo in the header

If you check page title, `<previous page> - Le Classement des Associations` but i expected that `<previous page>` was removed (as the first time you load `/`)

Here the repo: https://github.com/Barbapapazes/le-classement.fr/pull/155

### Reproduction

https://le-classement-fr-git-fix-seo-barbapapazes.vercel.app/

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz
    Memory: 2.09 GB / 15.88 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.3.1 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.54), ChromiumDev (110.0.1556.0)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by harlan-zw** [comment]
Hey, thanks for the code/reproduction. Very helpful.

I think the issue is actually an upstream issue with nuxt/content. If you change it to this it should work:

```
head.title: null
```

**Comment by Barbapapazes** [comment]
Yes, it seems that title is not update because of this code.

https://github.com/nuxt/content/blob/main/src/runtime/composables/head.ts#L22

When title is null, it is not pass to head.

**Comment by Barbapapazes** [comment]
It works with `title` and `head.title` to `null`. Thanks for your answer.

**Comment by Barbapapazes** [comment]
The property `og:title` is not updated (same reproduction).

**Comment by Barbapapazes** [comment]
Maybe there is something to do here: https://github.com/unjs/unhead/blob/main/packages/addons/src/plugins/inferSeoMetaPlugin.ts#L52

**Comment by harlan-zw** [comment]
not a massive problem as og:image is only for robots on initial load, I'll investigate though

**Comment by Barbapapazes** [comment]
Thanks man for the information! 

The solution could be to give a default value to this in case of undefined value?
