### ISSUE TITLE
[Feature Request] Add support for a more dynamic configuration

### ISSUE THREAD

**Issue by madebyfabian** [harlan-zw/nuxt-seo-kit#20]
### Clear and concise description of the problem

Me again 😄. Just a smaller feature request:

Before using this module, I was defining a dynamic title template (and therefore the site name) based on some external properties, inside `app.vue`:

```ts
const prefix = process.env.NODE_ENV === 'development' ? '⚙️ ' : ''
const dbResult = {
  siteName: '', // some value that is loaded from a database
  description: '', // some value that is loaded from a database
}

useSeoMeta({
  title: 'Home',
  titleTemplate: `${prefix}%s — ${dbResult.siteName || 'Default Website'}`,
  description: dbResult.description || undefined,
})
```

This was working fine, and allowed me fine-grained control about how to display the title. E.g. on dev, I add a `⚙️` emoji onto the beginning to differentiate the tabs. And, most importantly, the siteName coming from a dynamic source.

`nuxt-seo-kit` overrides these and since they are not defined in the `nuxt.config.ts`, because they need to be dynamic, it uses the default values from the plugin, overriding both my `titleTemplate` and my `description` meta.

```html
<meta property="og:site_name" content="Nuxt Playground">
<meta name="description" content="My Nuxt v3 website.">
<meta property="og:description" content="My Nuxt v3 website.">
```

1. Is there a way to make a dynamic site name work? I tried doing `<SeoKit :siteName="siteTitle" />` but this does not have an effect, the meta tag is still `Vue Playground` even though the variable `siteTitle` is definitely defined.

2. Is there a way to make the `titleTemplate` from seo meta work? I know there is `runtimeConfig.public.titleSeparator` but this just acts as a setting to set the title to `title seperator title` without further config.

### Suggested solution

- Add support for defining the properties of this plugin dynamically, e.g. with the `<SeoKit />` inside `app.vue`
- Add support for `titleTemplate`

### Alternative

- Env variables, but it's not really possible to fetch something from the DB and set an env variable for this value.

### Additional context

```bash
- Operating System: `Darwin`
- Node Version:     `v16.18.1`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.0.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `extends`, `modules`, `runtimeConfig`, `linkChecker`, `sitemap`, `image`, `turnstile`, `typescript`, `build`, `nitro`, `app`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.2.0`, `@nuxt/image-edge@1.0.0-27907872.f4dd19d`, `@nuxtjs/turnstile@0.1.2`, `nuxt-typed-router@2.2.1`
- Build Modules:    `-`

```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by harlan-zw** [comment]
Hey @madebyfabian 

This should be solved in in 1.2.1:
- titleTemplate is now root from the nuxt.config, so easier to override 
- you can pass props to SeoKit

**Comment by madebyfabian** [comment]
Hey @harlan-zw Thank you very much 😇

**Comment by madebyfabian** [comment]
@harlan-zw Thank you again so much, I just implemented it into my project and it works like a charm. Allowing me to inject a dynamic template with dynamic siteName coming from a DB call inside `app.vue`.
