### ISSUE TITLE
[Feature Request] Don't include components in build that are never used

### ISSUE THREAD

**Issue by madebyfabian** [harlan-zw/nuxt-seo-kit#24]
### Clear and concise description of the problem

Hey :) Currently, I am not using the

Client
- `OgImageBasic.island`
- `Breadcrumbs`

Server
- `OgImageStatic`
- `OgImageDynamic`
- `OgImageScreenshot`
- `OgImageBasic.island`
- `defineOgImage`
- `Breadcrumbs`

Components. Though they are all getting injected into my build

![Bildschirm­foto 2023-02-06 um 06 30 52](https://user-images.githubusercontent.com/32813692/216891148-d220430d-d3df-4bca-b4f0-1727e6e37aaa.jpg)
![Bildschirm­foto 2023-02-06 um 06 31 01](https://user-images.githubusercontent.com/32813692/216891167-52d75157-d8fe-4c53-b3fa-b63967cb3c3b.jpg)

This is something I'd like to avoid, though not being a real issue I think due to their small sizes.

Thanks in advance!

### Suggested solution

Dynamically load components based on if they are actually used, if that is somehow possible.

### Alternative

If not, maybe consider adding options to this module to not include certain features into the build.

### Additional context

See https://github.com/dargmuesli/nuxt-cookie-control/issues/37 for a similar issue

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by harlan-zw** [comment]
I'd agree these components shouldn't be global.

They were originally set up like this to get around a Nuxt layer issue and to add native support for nuxt/content integrations.

I don't consider it an issue outside of aesthetics though. Bundled components in the server should not have any real performance cost. Anyway, if you inspect the server bundle you'll see `NuxtWelcome` in there which is ~50kb :eyes: 

Will see what I can do though

**Comment by madebyfabian** [comment]
@harlan-zw No stress at all, just always better to have less stuff in a bundle when projects grow. And since I want to use the `nuxt-seo-layer` to be used inside my https://github.com/madebyfabian/nuxt-wordpress layer (layers inside layers, oh nuxt is awesome!!), I want it to be as clean as possible.

Yeah this `NuxtWelcome` is driving me nuts haha. I've never use it obviously, but it's getting included in some wierd way in my project. I tried to create a minimal reprod but without any chance. Maybe it's getting imported by a module I use.

**Comment by harlan-zw** [comment]
Hey @madebyfabian, this should all no longer be bundled if not used as of v1.2.3

**Comment by madebyfabian** [comment]
@harlan-zw You're awesome man, appreciate it 🙏🏻💚 #nuxters
