### ISSUE TITLE
Should the file name be hashed?

### ISSUE THREAD

**Issue by toniengelhardt** [harlan-zw/nuxt-seo-kit#28]
### Details

I think some SM services cache the OG image once added. Would it make sense to add a hash to the image filename to force refresh, aka. `og.png` to `og.5l2nm6.png`? Not sure if it makes sense...

It might also be that the service then cannot find the image anymore and shows nothing at all...

**Comment by harlan-zw** [comment]
> It might also be that the service then cannot find the image anymore and shows nothing at all...

I actually had it hashed initially, but run into this issue so I disabled it.

It may be possible to add a server middleware that allows you to access the image using some hashed pattern that would always just return the latest.

Thoughts?

**Comment by toniengelhardt** [comment]
Then I think the current implementation is the correct solution and we'll have to just wait for the platforms to update the cache. Closing and thanks for clarifying 🙏🏽
