### ISSUE TITLE
Integrate `<DebugHead />` and `<SchemaOrgDebug/>` in Nuxt Devtools

### ISSUE THREAD

**Issue by optimistic-raisin** [harlan-zw/nuxt-seo-kit#29]
### Clear and concise description of the problem

N/A

### Suggested solution

Now that we have Nuxt Devtool, we can perhaps add these components as a module in Devtool.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by harlan-zw** [comment]
Thanks for the issue, this is definetly planned :)

**Comment by harlan-zw** [comment]
This is supported as of latest @nuxtseo/module version.
