### ISSUE TITLE
head.use is not a function

### ISSUE THREAD

**Issue by Ben-VP** [harlan-zw/nuxt-seo-kit#3]
### Describe the bug

After installing Nuxt SEO I try and launch my dev environment using 'yarn dev' and I get the following error.

[nuxt] [request error] [unhandled] [500] head.use is not a function    

<img width="868" alt="CleanShot 2022-12-31 at 19 52 14@2x" src="https://user-images.githubusercontent.com/59267857/210153213-caa47105-bdcc-4381-8622-f610d48b199a.png">

### Reproduction

Followed the install instructions up until the optional step of the OgImages.

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 36.59 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.9.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.1 - /opt/homebrew/bin/npm
  Browsers:
    Firefox Developer Edition: 107.0
    Safari: 16.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by harlan-zw** [comment]
Hey @Ben-VP 

This is most likely due to one of your dependencies using an older version of @vueuse/head. You can debug this with `yarn why @vueuse/head`.

Nuxt is pinned to the latest version, so if you don't have anything depending on an earlier version it should fix itself. If not try and also delete the lock file & node_modules folder.

**Comment by Ben-VP** [comment]
> 

For some reason, Nuxt was using an outdated version of `@vueuse/head`. Deleting the lock file and the node_modules folder and running yarn install sorted this.

Thank you!
