### ISSUE TITLE
adding the `extends:` property in `nuxt.config.ts` file throws error in modules `Type instantiation is excessively deep and possibly infinite.`

### ISSUE THREAD

**Issue by xrayian** [harlan-zw/nuxt-seo-kit#31]
### Describe the bug

my nuxt3 application uses  3 modules 
```typescript
export default defineNuxtConfig({
  modules: ["@nuxtjs/tailwindcss", "nuxt-icon", "@pinia/nuxt"],
  //...
})
```
but after adding the `nuxt-seo-kit` plugin, adding the 
`extends: ["nuxt-seo-kit"]` line in `nuxt.config.ts` my IDE is throwing this error
`Type instantiation is excessively deep and possibly infinite.ts(2589)`

Removing this line fixes the module issue. Running my dev server with this issue results in this error on my browser
```
500
Cannot read properties of undefined (reading 'replace')

at D:\incognilog-nuxt-3\node_modules\nuxt-unhead\dist\runtime\plugin.mjs:40:18
at fn (D:\incognilog-nuxt-3\node_modules\nuxt\dist\app\nuxt.mjs:151:27)
at Object.callAsync (/D:/incognilog-nuxt-3/node_modules/unctx/dist/index.mjs:49:19)
at callWithNuxt (D:\incognilog-nuxt-3\node_modules\nuxt\dist\app\nuxt.mjs:153:23)
at applyPlugin (D:\incognilog-nuxt-3\node_modules\nuxt\dist\app\nuxt.mjs:97:29)
at Module.applyPlugins (D:\incognilog-nuxt-3\node_modules\nuxt\dist\app\nuxt.mjs:107:11)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async createNuxtAppServer (D:\incognilog-nuxt-3\node_modules\nuxt\dist\app\entry.mjs:29:7)
at async default (/D:/incognilog-nuxt-3/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:27:18)
```

### Reproduction

will add if necessary

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (6) x64 AMD Ryzen 5 3500X 6-Core Processor
    Memory: 4.84 GB / 15.95 GB
  Binaries:
    Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.3.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.755.0), Chromium (110.0.1587.41)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [ ] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by xrayian** [comment]
my bad Updating to Nuxt 3.2.0 fixed the error.

**Comment by harlan-zw** [comment]
No problem, glad you could sort it :)

**Comment by Elben9** [comment]
i have same question.  when i add `extends: ['nuxt-seo-kit']`， `nuxt.config.ts  modules`throw error: `Type instantiation is excessively deep and possibly infinite`
my Nuxt version is 3.2.2

**Comment by jamesparkes** [comment]
also experiencing the same issue with nuxt version 3.2.2

**Comment by robert-moore** [comment]
Experiencing this with nuxt version 3.3.1 after adding nuxt-seo-kit

<img width="608" alt="image" src="https://user-images.githubusercontent.com/4934366/227710275-7733686e-5c2d-4511-9f9c-2991fcb7b6a3.png">

**Comment by robert-moore** [comment]
It appears this is resolved by running nuxi and regenerating the types

**Comment by jamesparkes** [comment]
@robert-moore this also appears to be cleared up for me after upgrading to the latest nuxt (3.3.2) and nuxt-seo-kit (1.3.5). thanks!

**Comment by jamesparkes** [comment]
@robert-moore @harlan-zw i am seeing an issue w/ the title separator no longer rendering after the respective nuxt and nuxt-seo-kit upgrades. not sure if you are seeing the same thing.

**Comment by packet-sent** [comment]
I am having the same issue on nuxt version 3.3.2 (I tried regenerating the types and nothing changed),
![image](https://user-images.githubusercontent.com/72577411/229332520-3771268a-1b62-4f9e-92f6-1bb7fa96abc8.png)

**Comment by harlan-zw** [comment]
This is an upstream issue with Nuxt. The v2 of the module moves away from using a layer and should also help solve the issue.
