### ISSUE TITLE
[500] You may forget to apply app.use(head) 

### ISSUE THREAD

**Issue by reslear** [harlan-zw/nuxt-seo-kit#32]
#### is run `pnpm dev`

<img width="1270" alt="Screenshot 2023-02-15 at 11 44 45" src="https://user-images.githubusercontent.com/12596485/219005967-75540e2d-466a-4d22-99cb-de5e1c88e5d9.png">

<img width="1697" alt="Screenshot 2023-02-15 at 11 46 25" src="https://user-images.githubusercontent.com/12596485/219006333-86d2ccc0-5720-487f-b082-4111571a4592.png">

#### is run `pnpm build`

<img width="1417" alt="Screenshot 2023-02-15 at 12 01 13" src="https://user-images.githubusercontent.com/12596485/219009950-68260867-eae0-4cf6-8907-772536d5b9b1.png">

but working well is exclude `extends: ['nuxt-seo-kit']`

I can't figure out which way to look (

```ts
{
  "name": "website",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxi build",
    "build:static": "nuxi generate",
    "dev": "nuxi dev --port 3010",
    "generate": "nuxi generate",
    "preview": "nuxi preview",
    "start": "node .output/server/index.mjs"
  },
  "dependencies": {
    "@segment/analytics-next": "^1.51.0",
    "@unocss/transformer-variant-group": "^0.49.4",
    "@vueuse/core": "^9.12.0",
    "@walletconnect/web3-provider": "^1.8.0",
    "axios": "^1.3.3",
    "lottie-web": "^5.10.2",
    "nuxt-swiper": "^1.0.0",
    "std-env": "^3.3.2",
    "unocss-preset-scrollbar-hide": "^1.0.1",
    "vite-compatible-readable-stream": "^3.6.1",
    "vue-loading-overlay": "^6.0.3",
    "vue-use-web3modal": "workspace:*",
    "web3": "^1.8.2",
    "ws": "^8.12.1"
  },
  "devDependencies": {
    "@nuxt/devtools": "^0.1.2",
    "@nuxt/image-edge": "1.0.0-27919678.2f5b64b",
    "@types/node": "^18.13.0",
    "@unocss/nuxt": "^0.49.4",
    "@unocss/transformer-directives": "^0.49.4",
    "@vueuse/nuxt": "^9.12.0",
    "fast-glob": "^3.2.12",
    "nuxt": "3.2.0",
    "nuxt-seo-kit": "^1.2.3",
    "nuxt-unhead": "^1.3.4",
    "postcss": "^8.4.21",
    "postcss-nested": "^6.0.0",
    "web3-utils": "^1.8.2"
  },
  "engines": {
    "node": ">=18",
    "pnpm": ">=7"
  }
}
```

### System Info

```Shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M2
    Memory: 1.07 GB / 24.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.0 - ~/Library/Caches/fnm_multishells/42035_1676455696779/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/42035_1676455696779/bin/yarn
    npm: 9.3.1 - ~/Library/Caches/fnm_multishells/42035_1676455696779/bin/npm
  Browsers:
    Chrome: 110.0.5481.96
    Safari: 16.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by DmitrySkakun** [comment]
Faced the same problem today

**Comment by harlan-zw** [comment]
Hi @reslear and @DmitrySkakun 

You both seem to have a dependency on the old version of @vueuse/head (0.9.8). 

I'm guessing one of your other dependencies has it hardcoded to this version. The reason why nuxt-seo-kit throws an error with it is nuxt-seo-kit uses the latest features within @vueuse/head, unlike Nuxt itself.

 Could you run `pnpm why @vueuse/head` or `npm why @vueuse/head` and paste the output?

**Comment by reslear** [comment]
hi @harlan-zw thx for fast answering :)

<img width="429" alt="Screenshot 2023-02-15 at 12 23 40" src="https://user-images.githubusercontent.com/12596485/219014295-a6400475-8759-4654-89e4-a08a92e687b7.png">

this seems to have happened after upgrading to nuxt 3.2 and adding nuxt devtools...

**Comment by harlan-zw** [comment]
Hm this is really strange, doesn't say you have had the old vueuse/head as a dependency. :thinking: 

Could you try clearing your node_modules folder and re-install deps with as `pnpm i --shamefully-hoist`

**Comment by reslear** [comment]
@harlan-zw also you right, is click to error i'm jumping to @vueuse/head (0.9.8).

so i install in deps `@vueuse/head` as `pnpm add @vueuse/head@latest` - and work fine (    "@vueuse/head": "^1.0.25")

thx for support :) have a good day 😀
