### ISSUE TITLE
Schema.org LD+JSON data not being populated with nuxt-seo-kit

### ISSUE THREAD

**Issue by GeorgeForse** [harlan-zw/nuxt-seo-kit#38]
### Describe the bug

The Schema.org Component, even when setup according to the documentation for nuxt-seo-kit, will output:
`<script type="application/ld+json" id="schema-org-graph" data-h-81c305=""></script>` with no LD+JSON data.

If I install nuxt-schema-org separately, the LD+JSON data populates as expected with no further configuration change.

This bug is also currently occurring on [harlanzw.com](https://harlanzw.com/) as of  2023-03-01 18:50 UTC

My Nuxt environment:
- Nuxt 3.2.3
- Nuxt-SEO-Kit 1.3.1

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 17.03 GB / 31.91 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1325.0), Chromium (110.0.1587.57)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by harlan-zw** [comment]
Hey @GeorgeForse, thanks for the issue!

Can you try to clear your lock file + re-install? I believe this was a nuxt / unhead dependency issue. I did that for my site and it looks okay now.

Otherwise happy to dig into it further

**Comment by GeorgeForse** [comment]
@harlan-zw that worked, thank you!
