### ISSUE TITLE
Unable to run on Windows

### ISSUE THREAD

**Issue by ennioVisco** [harlan-zw/nuxt-seo-kit#39]
### Describe the bug

I get this error on adding it to my project. Any intuition on why? 
![image](https://user-images.githubusercontent.com/740025/222276537-ff2b6515-6887-4a0d-8b46-15fa10ad567f.png)

Reproduction: follow the installation guide, then run `nuxt dev`.

I currently am not providing a sandboxed reproduction as I'm not aware of any online sandbox for Windows. Although I'll happily work on one if considered relevant!

### Reproduction

-

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (4) x64 Intel(R) Core(TM) i3-8350K CPU @ 4.00GHz
    Memory: 3.37 GB / 15.96 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.4.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 110.0.5481.177
    Edge: Spartan (44.22621.1265.0), Chromium (110.0.1587.57)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by harlan-zw** [comment]
Hey @ennioVisco ! Thanks for the issue, could you try the latest version 1.3.2 and let me know how that goes

**Comment by ennioVisco** [comment]
Thanks! Fixed in https://github.com/harlan-zw/nuxt-seo-kit/commit/fbd25a924df3e1ae7d81b35f3b44d48d5082a966
