### ISSUE TITLE
Integrate with nuxt-i18n

### ISSUE THREAD

**Issue by ptdev** [harlan-zw/nuxt-seo-kit#4]
### Details

Hi there, 

Thanks for building this module.

I have a question though: Is this usable with nuxt-i18n? Or how can one use definePageMeta() to get the title and descriptions on the correct language?

Cheers

**Comment by harlan-zw** [comment]
Hey, thanks for the issue.

Full nuxt-i18n integration is planned once it's stable. You can look at how the SeoKit component works to see how you might set up your own page meta parsing in the mean time.

**Comment by ptdev** [comment]
Hey,

Thanks for the quick reply.

Will do as recommended in the meanwhile until the stable hits.

Thanks again and happy new year, cheers!

**Comment by dargmuesli** [comment]
For me, links generated by nuxt-i18n lead to the following error. I don't know of an option to configure nuxt-i18n to generate relative links.

```
Absolute link, should be relative                                                                                                              nitro 12:14:27
   <link rel="alternate" href="https://localhost:3000/privacy-policy" hreflang="x-default">
```

**Comment by harlan-zw** [comment]
> For me, links generated by nuxt-i18n lead to the following error. I don't know of an option to configure nuxt-i18n to generate relative links.
> 
> ```
> Absolute link, should be relative                                                                                                              nitro 12:14:27
>    <link rel="alternate" href="https://localhost:3000/privacy-policy" hreflang="x-default">
> ```

Thanks, it should probably not scan anything in `<head>` tbh

**Comment by dargmuesli** [comment]
Also, `Breadcrumbs` currently don't account for suffixes like `/en` or `/de`. But I'm almost sure that's already on your radar :wink:
