### ISSUE TITLE
Strict type checking

### ISSUE THREAD

**Issue by ennioVisco** [harlan-zw/nuxt-seo-kit#40]
### Clear and concise description of the problem

Since `nuxt-seo-kit` is provided as a layer (why so? couldn't it be a module?), it will inherit the settings of the project where it is used. 

In particular, in my project I have strict typechecking enabled, which is currently not used by this project.

### Suggested solution

Change:

```ts
// layer/nuxt.config.ts
export default defineNuxtConfig({
    // ...
   typescript: {
    strict: true,
    typeCheck: true,
  },
})
```

And solve the related vue-tsc issues.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by harlan-zw** [comment]
Hey @ennioVisco 

I chose to make it a layer initially as I wasn't sure what kind of scope I wanted for the project and a layer is much more flexible. I may consider moving back to a module in a v2 release.

Can you provide what error you're getting exactly? I've tried to replicate the issue and just got

```bash
[vue-tsc] Found 0 errors. Watching for file changes.
```

**Comment by ennioVisco** [comment]
I'm digging in and it seems they are related to the fact that I'm importing it by layer:

- A set of errors relating to overlapping composables and types (I already had some things called `Breadcrumbs`).
- A set of error related to Nuxt options, perhaps layers are injected at runtime and therefore the new options are missing? (screen)
<img width="707" alt="Screenshot 2023-03-06 at 10 03 39" src="https://user-images.githubusercontent.com/740025/223064954-847eb18e-3403-4b8f-906e-2c3bd185c2fd.png">

**Comment by ennioVisco** [comment]
> 

With deeper thoughts, I suspect the type checking will always fail when interpreted as a layer @harlan-zw . I guess in your case it was not because the external project must enable strict type checking, not `nuxt-seo-kit`. 
Does this make sense to you? Or would you prefer to have a reproduction? (I can work on it).

**Comment by harlan-zw** [comment]
> > 
> 
> With deeper thoughts, I suspect the type checking will always fail when interpreted as a layer @harlan-zw . I guess in your case it was not because the external project must enable strict type checking, not `nuxt-seo-kit`. Does this make sense to you? Or would you prefer to have a reproduction? (I can work on it).

Yes there isn't a way to get around this with that code (and having it as a layer). Either the typings won't exists or they will exist and a @ts-expect-error with throw an error.

I plan to move nuxt-seo-kit to a module in v2 to resolve this, until then there's not much I can do (besides removing all of this code, which may also be possible).

**Comment by harlan-zw** [comment]
This actually may be fixed in 1.3.5, I forgot I could use `@ts-ignore`, forced myself out of using it generally but it seems ideal in this situation.

**Comment by matkappert** [comment]
Hey @harlan-zw, 

I just tried 1.3.5 and all but one error is left.

```bash
node_modules/nuxt-seo-kit/modules/nuxt-seo-kit/module.ts:87:35 - error TS2558: Expected 0 type arguments, but got 1.

87         latestTag = (await $fetch<any>('https://ungh.unjs.io/repos/harlan-zw/nuxt-seo-kit/releases/latest')).release.tag
```

**Comment by ennioVisco** [comment]
> Hey @harlan-zw,
> 
> I just tried 1.3.5 and all but one error is left.
> 
> ```shell
> node_modules/nuxt-seo-kit/modules/nuxt-seo-kit/module.ts:87:35 - error TS2558: Expected 0 type arguments, but got 1.
> 
> 87         latestTag = (await $fetch<any>('https://ungh.unjs.io/repos/harlan-zw/nuxt-seo-kit/releases/latest')).release.tag
> ```

I don't have this issue!

**Comment by ennioVisco** [comment]
> Hey @harlan-zw,
> 
> I just tried 1.3.5 and all but one error is left.
> 
> ```shell
> node_modules/nuxt-seo-kit/modules/nuxt-seo-kit/module.ts:87:35 - error TS2558: Expected 0 type arguments, but got 1.
> 
> 87         latestTag = (await $fetch<any>('https://ungh.unjs.io/repos/harlan-zw/nuxt-seo-kit/releases/latest')).release.tag
> ```

I don't have this issue!

**Comment by dargmuesli** [comment]
v2 of nuxt-seo-kit will be available as a module: https://www.npmjs.com/package/@nuxtseo/module

**Comment by ennioVisco** [comment]
Addressed in V2.
