### ISSUE TITLE
`og:title` is broken

### ISSUE THREAD

**Issue by Barbapapazes** [harlan-zw/nuxt-seo-kit#41]
### Describe the bug

The `og:title` is broken.

![image](https://user-images.githubusercontent.com/45267552/223230603-65de7a3f-0fa8-4a5c-90c3-78fb1453b5c4.png)

But here the `title`

![image](https://user-images.githubusercontent.com/45267552/223230656-41092013-b005-4f30-9dc6-2e8eeab315e3.png)

### Reproduction

https://stackblitz.com/edit/nuxt-starter-88pcse?file=app.vue

### System / Nuxt Info

```Shell
/
```

**Comment by harlan-zw** [comment]
Thanks @Barbapapazes & @modbender 

This appears to be fixed in v1.3.3 (https://stackblitz.com/edit/nuxt-starter-dkfzzb?file=package.json)

Please let me know if you have any issues

**Comment by Barbapapazes** [comment]
Hello @harlan-zw,

Seems solved for me! Thanks  🙏
