### ISSUE TITLE
Is it possible to enable only some of the modules?

### ISSUE THREAD

**Issue by plcdnl** [harlan-zw/nuxt-seo-kit#42]
It would be very helpful if i could disable sitemaps and robots, which I generate directly from the cms

**Comment by harlan-zw** [comment]
Hi @plcdnl 

You can disable the sitemap module by putting this in your nuxt config.

```ts
sitemap: {
  enabled: false,
  devPreview: false,
}
```

I've also just pushed out a release for nuxt-simple-robots which will let you do

```ts
robots: {
  enabled: false,
}
```

Will close this once SeoKit is using this version

**Comment by plcdnl** [comment]
Hi @harlan-zw,  forgive me for bothering again, but if i disable the robots i get the following error:

`ERROR  [unimport] failed to find "defineRobotMeta" imported from "#imports"`

**Comment by alexrodriguezjob** [comment]
Hi @harlan-zw the same issue is ocurring to me `ERROR  [unimport] failed to find "defineRobotMeta" imported from "#imports"`, once I turn off the robots module

**Comment by gcyugurten** [comment]
i'm facing the same issue, any solution please?

**Comment by harlan-zw** [comment]
You will need to upgrade to the v2 beta if you'd like to fix this unfortunately, there isn't a workaround for v1 atm.

https://nuxtseo.com/nuxt-seo/getting-started/migration-guide
