### ISSUE TITLE
publish(cloudflare): workers.api.error.script_too_large [code: 10027]

### ISSUE THREAD

**Issue by oritwoen** [harlan-zw/nuxt-seo-kit#43]
### Describe the bug

When trying to publish on cloudflare workers with the module enabled, I get the following error.

The build is created correctly. Everything works fine locally. I know it's a bug caused by this module, after disabling it `publish` works fine too.

Probably by https://github.com/harlan-zw/nuxt-og-image

```
Here are the 2 largest dependencies included in your script:

  - .output/server/index.mjs - 2070.46 KiB
  - wrangler-module-CompiledWasm:./26c174f66255792aa5c733cf3ab740b54120c2b7-svg2png.wasm - 0.56 KiB
  If these are unnecessary, consider removing them
  
    workers.api.error.script_too_large [code: 10027]
```

**Comment by harlan-zw** [comment]
Hi

The free tier is very limited, if you need to generate og images dynamically then I'd recommend upgrading.

Otherwise you can just disable satori in your nuxt.config like so:

```ts
ogImage: {
   satoriProvider: false
}
```
