### ISSUE TITLE
Breadcrumb outputs nested page title in a crumb

### ISSUE THREAD

**Issue by stijn-ways** [harlan-zw/nuxt-seo-kit#46]
### Describe the bug

Hi guys,

When I'm going to `/blog/de-ultieme-beginnersgids-voor-zoekmachine-optimalisatie-seo`, my breadcrumb wil display as followed:

![image](https://user-images.githubusercontent.com/127141824/229128090-7fe6ad99-8cd8-4ce8-8432-3da2c213b36b.png)

As you can see, the word "Blog" is also presented in the last item.

Could you please take a look at it?

### System / Nuxt Info

```Shell
{
  "devDependencies": {
    "@nuxtjs/tailwindcss": "^6.6.5",
    "@vueuse/core": "^9.13.0",
    "@vueuse/nuxt": "^9.13.0",
    "nuxt": "^3.3.2",
    "nuxt-seo-kit": "^1.3.5",
    "prettier": "^2.8.7",
    "prettier-plugin-tailwindcss": "^0.2.5",
    "sass": "^1.60.0"
  },
  "dependencies": {
    "@storyblok/nuxt": "^5.3.0"
  }
}
```

**Comment by harlan-zw** [comment]
Hey @stijn-ways, thanks for the issue.

I've pushed up a fix in v1.3.6 and have updated the docs so the inferring is clearer.
