### ISSUE TITLE
Canonical URL isn't updating on page change

### ISSUE THREAD

**Issue by Ben-VP** [harlan-zw/nuxt-seo-kit#5]
### Describe the bug

When using the Nuxt <Link hid="canonical" rel="canonical" href="https://website.com"/> this will automatically change on page change.

However, when using Nuxt-seo-kit this doesn't update unless the page is refreshed.

The og:URL will update on page change but the canonical URL will stay the same.

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 96.31 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.9.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.1 - /opt/homebrew/bin/npm
  Browsers:
    Firefox Developer Edition: 109.0
    Safari: 16.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by harlan-zw** [comment]
Hey @Ben-VP 

Thanks for the issue. The canonical URL was set not to be reactive due to robots only needing it on the initial server response. I've updated it to be reactive just in case something needs it dynamically though

The change is available in 0.4.7

**Comment by Ben-VP** [comment]
Thanks @harlan-zw, seems to work but after a few page navigations it disappears.

**Comment by harlan-zw** [comment]
I can't seem to replicate it disappearing, any chance of a reproduction repo or some more details? 

Again wouldn't cause any issues as only the initial load is considered by robots.
