### ISSUE TITLE
It seems that screenshot does not work with Docus

### ISSUE THREAD

**Issue by Barbapapazes** [harlan-zw/nuxt-seo-kit#51]
### Describe the bug

I'm currently building a docs using Docus with the `<OgImageScreenshot />` but it doesn't work with Docus. The screenshot is just a white screen and I don't understand why.

https://aneoconsulting.github.io/armonik-docs-theme/__og_image__/og.png

### Reproduction

https://github.com/aneoconsulting/armonik-docs-theme

### System / Nuxt Info

```Shell
------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.3.2`
- Nitro Version:    `2.3.2`
- Package Manager:  `pnpm@8.1.0`
- Builder:          `vite`
- User Config:      `app`, `extends`, `content`, `runtimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

**Comment by harlan-zw** [comment]
I'm presuming this is fixed with the v3 of OG Image, I have it working with one of my sites.

Let me know if that's not the case.
