### ISSUE TITLE
It is possible to upgrade all deps of nuxt-seo-kit to use @nuxt/kit 3.4

### ISSUE THREAD

**Issue by jordan-boyer** [harlan-zw/nuxt-seo-kit#52]
### Details

If you want to upgrade de nuxt 3.4 you need to use a workaround for it to work with other modules that don't use @nuxt/kit 3.4. 

It's possible to upgrade all dependencies so that they use @nuxt/kit 3.4. 

I'm open to do a PR on all necessary repository =)

**Comment by harlan-zw** [comment]
Hey @jordan-boyer, thanks for the issue 

Would you mind clarifying what the issue is with non 3.4 modules? I am not aware of this limitation.

I intend to bump all versions to 3.4, some are already supporting it otherwise

**Comment by jordan-boyer** [comment]
Ho my bad, i didn't explain what the problem was. 

I think it's better for me to link the issue on the nuxt repository: https://github.com/nuxt/nuxt/issues/20209

In short it's a problem with the consola dep, which can fail if you're using a monorepo or a workspace setup (or even pnpm)

**Comment by harlan-zw** [comment]
Should be solved with 1.3.8, let me know if you have any issues with it :)
