### ISSUE TITLE
Specify config via `site` option

### ISSUE THREAD

**Issue by tobiasdiez** [harlan-zw/nuxt-seo-kit#56]
### Describe the bug

This is between a feature request and a bug report. The readme mentions that one should specify `siteName` etc via `runtimeConfig`. However, there is also the `site` config option in `nuxt.config.ts`. Setting 
```ts
  site: {
    siteName: 'JabRef',
    siteDescription:
      'A free reference manager that helps you to discover, collect, organize and cite your scholarly literature and research in an efficient way.',
  },
```
however doesn't have any effect and the `<title>` tag renders as `%siteName`.

### System / Nuxt Info

```Shell
- Operating System: Windows_NT
- Node Version:     v19.8.1
- Nuxt Version:     3.4.2
- Nitro Version:    2.3.3
- Package Manager:  yarn@3.3.0
- Builder:          vite
- User Config:      extends, alias, nitro, experimental, app, modules, runtimeConfig, routeRules, tailwindcss, graphqlServer, content, naiveUI, site, vite
- Runtime Modules:  @nuxtjs/tailwindcss@6.6.6, @huntersofbook/naive-ui-nuxt@0.6.0, @pinia/nuxt@0.4.9, ./modules/storybook, nuxt-graphql-server@1.2.2, @nuxt/content@2.4.3, storybook-vue-addon/nuxt, @nuxt/devtools@0.3.1, nuxt-icon@0.3.3, @vee-validate/nuxt@4.8.6
- Build Modules:    -
```

**Comment by annymosse** [comment]
for 404 pages `site.name` it doesn't work unless using `runtimeConfig.public.site.name`.

**Comment by annymosse** [comment]
by using `@nuxtseo` I found a bug when setting `site.name` it doesn't work on 404 pages unless using `runtimeConfig.public.site.name`.

**Comment by harlan-zw** [comment]
Can you confirm the version? The recommendation for v2 is to use the `site` key in nuxt.config.
