### ISSUE TITLE
Social Share

### ISSUE THREAD

**Issue by CareTiger** [harlan-zw/nuxt-seo-kit#64]
### Details

I have been using the vue-social-share (https://www.npmjs.com/package/vue-social-sharing) and not too happy with it. Sebastian (@atinux) told me this module has a social share option but it wasn't obvious from the README.md.   Is it available , if so Can you point me in the right direction and any examples if any? I would like to enable it for my blog posts to share on one click with Facebook/Twitter/LinkedIn/Instagram.  Thanks

**Comment by zernonia** [comment]
Not sure there's Social Sharing here.. but you can check out NuxtLego

https://nuxt-lego.vercel.app/docs/components/social-share

**Comment by harlan-zw** [comment]
Yes seems like the above is what you're after, thanks @zernonia
