### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by DidoMarchet** [harlan-zw/nuxt-seo-kit#68]
### Details

Hi,

I'm trying to figure out how to use the Nuxt SEO kit with i18n. I've integrated the SEO for i18n and I'm wondering if it's necessary to include i18n in the head meta to get the correct hreflang, etc. (I'm guessing the answer is yes).

However, I've noticed that the language in the HTML tag isn't updated by the i18n SEO meta. So, even if I'm on the Italian version, it still shows lang="en".

Apologies for the broad question, but I'd like to know if anyone has developed a multilingual SEO website using Nuxt3, i18n, and the Nuxt SEO kit.

Thanks and best regards,

Davide

**Comment by harlan-zw** [comment]
Hey Davide, thanks for the question.

Nuxt SEO KIt v1 does not have support for i18n, v2 is being developed with i18n support among many other fundamental improvements.

**Comment by DidoMarchet** [comment]
Hi,
thanks for the answer.

Kind regards,
Davide
