### ISSUE TITLE
[v2/docs] badges don't appear properly in dark mode

### ISSUE THREAD

**Issue by brc-dd** [harlan-zw/nuxt-seo-kit#70]
Hi, might wanna add `variant="ghost"` on `UButton` here:

https://github.com/harlan-zw/nuxt-seo-kit/blob/846e570af8e9c1c59e8f893329115c7366c645b0/docs/components/ShowcaseCard.vue#L59-L61

Without that things appear like this on [nuxtseo.com](https://nuxtseo.com/) in dark mode (button styles are affecting badge styles):

<img width="428" alt="image" src="https://github.com/harlan-zw/nuxt-seo-kit/assets/40380293/870f3457-6d4e-4ea0-89e9-c8ce066a0f4b">

**Comment by harlan-zw** [comment]
Haha thanks, have pushed up a fix.

Appreciate your recent bug reports!
