### ISSUE TITLE
Is this module still needed or should we use individual sub-modules?

### ISSUE THREAD

**Issue by stefanobartoletti** [harlan-zw/nuxt-seo-kit#72]
### Details

Sorry if this question might seem a bit unnecessary, but I'm not understanding if this collection module is still needed/recommended, or if it is better to use its submodules like `og-image`, `sitemap`, `robots`, and so on.

On the new documentation website, each module seems to be explicitly referenced as being installed separately, and there are no instructions to setup the whole SEO package.

Is this a case of still work-in-progress docs, or the installation strategy is indeed different now?

Thank you for your patience:  :)

**Comment by harlan-zw** [comment]
Hey @stefanobartoletti, thanks for the question. Sorry for the confusing roadmap with this module

There are plans for an official v2, but it requires all modules to be bumped a major. The big difference between v1 and v2 is that v1 only works when prerendering and the i18n support is limited, whereas this will be solved in v2.

While most the modules have this working, not all of them, so I still have 2 modules left to bump and a new module to release. However, I'll be pushing up some more beta versions in the next few days

**Comment by stefanobartoletti** [comment]
Thank for your reply, I think I will stick to V1 and upgrade when everything will be ready.

And thank you for the awesome work behind the modules  too✌️

**Comment by 9mm** [comment]
Hey @harlan-zw I was curious the status of i18n?

I'm starting an extensively large project that uses i18n, different currencies, etc. I've never used nuxt before and there are just so many SEO modules here it is a bit confusing.

Some questions:
* should we still use individual modules?
* the experimental module seems to include og tags, but theres a separate og module for that, which is right?

Currently the ones I'm looking to use are:

```
    "nuxt-og-image": "^2.0.13",
    "nuxt-schema-org": "^2.2.0",
    "nuxt-simple-sitemap": "^3.1.5",
```

```
    'nuxt-og-image',
    'nuxt-schema-org',
    'nuxt-simple-sitemap',
```

along with nuxt i18n module.

**Comment by dargmuesli** [comment]
You can use individual modules or check https://github.com/harlan-zw/nuxt-seo-kit/releases to see the status on nuxt-seo-kit v2.

**Comment by harlan-zw** [comment]
There is an initial migration guide for v2, it's currently in beta but feel free to try it out.

https://nuxtseo.com/nuxt-seo/getting-started/migration-guide

**Comment by stefanobartoletti** [comment]
@harlan-zw thanks!
