### ISSUE TITLE
Conflict with i18n when extending nuxt-seo-kit

### ISSUE THREAD

**Issue by LeCoupa** [harlan-zw/nuxt-seo-kit#80]
### Details

Hey :) There is an issue with the config file from i18n when we extends `nuxt-seo-kit` in `nuxt.config.ts`.

```ts
  // ...
  extends: [
    'nuxt-seo-kit',
  ],
  i18n: {
    vueI18n: './config/i18n.config.ts',
  }
```

We get the following error:

```
[@nuxtjs/i18n 11:50:20 PM]  WARN  Ignore Vue I18n configuration file does not exist at i18n.config on layer /Users/lecoupa/Documents/TheCompaniesAPI/thecompaniesapi-app/node_modules/.pnpm/nuxt-seo-kit@1.3.9_@unhead+vue@1.1.32_rollup@2.79.1_vue@3.3.4/node_modules/nuxt-seo-kit. Skipping...
```

When we stop extending `nuxt-seo-kit`, it works and the configuration file for i18n is taken into account. Do you have any idea how we can fix this? Is it a bug from this package or from i18n? 🙂

**Comment by dargmuesli** [comment]
Fixed in https://github.com/nuxt-modules/i18n/pull/2347
