### ISSUE TITLE
Typescript error `Cannot find module '#nuxt-seo-kit/config' or its corresponding type declarations.`

### ISSUE THREAD

**Issue by KamilBeda** [harlan-zw/nuxt-seo-kit#85]
### Describe the bug

I've noticed that if I run `npx nuxi typecheck` I get `Cannot find module '#nuxt-seo-kit/config' or its corresponding type declarations.` error coming from node_modules. I'm not sure if this is nuxt issue or this module issue, as far as I know typecheck shouldn't check npm packages for errors. 

Steps to reproduce:
1. create empty nuxt project using `npx nuxi@latest init my-app`
2. add nuxt-seo-kit according to [the docs](https://github.com/harlan-zw/nuxt-seo-kit)
3. run `npx nuxi typecheck`

### System / Nuxt Info

```Shell
------------------------------
- Operating System: Linux
- Node Version:     v18.17.1
- Nuxt Version:     3.7.0
- CLI Version:      3.7.2
- Nitro Version:    2.6.2
- Package Manager:  pnpm@8.6.11
- Builder:          -
- User Config:      devtools, extends
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

**Comment by jpengelbrecht** [comment]
yea it does not seem to like the new nuxt version

**Comment by harlan-zw** [comment]
Thanks for the issue. Please try out 1.3.10
