### ISSUE TITLE
OgImage explanation

### ISSUE THREAD

**Issue by sifferhans** [harlan-zw/nuxt-seo-kit#9]
### Details

Would it be possible to explain how to use the dynamic `OgImage` feature in the docs? 
Maybe I'm just stupid, but I can't get it to work properly, and I don't know if I do it right 😅

**Comment by Ben-VP** [comment]
What issue are you facing @sifferhans?

**Comment by sifferhans** [comment]
There arent any OgImages generated, it seems like
https://sigveh.no is the website

**Comment by Ben-VP** [comment]
Do you have `<OgImageScreenshot />` setup in your `app.vue`?

```
<template>
  <AppLayout>
    <SeoKit />
    <OgImageScreenshot />
    <NuxtPage />
  </AppLayout>
</template>
```

You can find some more information here https://github.com/harlan-zw/nuxt-og-image

**Comment by harlan-zw** [comment]
Hey @sifferhans 

To deploy using Vercel and have the screenshots generated you'll need to install a chromium instance, the package itself doesn't do this to avoid the binary overhead when installing the deps.

For my personal site I updated my build script to this and seems to work fine. You can see docs here: https://github.com/harlan-zw/nuxt-og-image#ci-build

```bash
npx playwright install && nuxi build
```

Will look to improve the documentation around this and make it more visible.

**Comment by sifferhans** [comment]
@harlan-zw Doesn't seem to work in my case.. 

I also noticed I hadn't [prerendered any pages](https://github.com/harlan-zw/nuxt-og-image#pre-render-routes).
The index route is now prerendered, but it doesn't look like it works either way. 😅

**Comment by harlan-zw** [comment]
Hey @sifferhans, going to close this with the v1 release https://github.com/harlan-zw/nuxt-og-image/releases/tag/v1.0.0. 

If you have any new issues would be amazing if you could open an issue on that repo, will happy to look into it anything.
