### ISSUE TITLE
[type] [v2] typechecking 

### ISSUE THREAD

**Issue by ennioVisco** [harlan-zw/nuxt-seo-kit#96]
### Describe the bug

I believe a question mark is missing at `Breadcrumb.vue`, line 60 :)
<img width="938" alt="image" src="https://github.com/harlan-zw/nuxt-seo-kit/assets/740025/1910b241-49a2-44fc-a18d-e82c27b24dd6">

**Comment by harlan-zw** [comment]
Thanks :) Should be fixed in nuxt-seo-ui v0.3.2

**Comment by ennioVisco** [comment]
@harlan-zw unfortunately not, I created a small pr to propose a fix: https://github.com/harlan-zw/nuxt-seo-ui/pull/1
