### ISSUE TITLE
`og:title` goes to `body`, not `head` :walking: 

### ISSUE THREAD

**Issue by dargmuesli** [harlan-zw/nuxt-seo-kit#97]
### Describe the bug

`<meta property="og:title" content="XYZ | nuxt-app" />` is part of `body`, but should be part of `head`.

### Reproduction

https://stackblitz.com/edit/github-dpzmzy-9b21pd?file=app.vue

### System / Nuxt Info

```Shell
------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.7.1
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      modules
- Runtime Modules:  @nuxtseo/module@2.0.0-beta.25
- Build Modules:    -
------------------------------
```

**Comment by harlan-zw** [comment]
Looks like the `og:title` tag was being appended to every single entry, if the last entry had `{ tagPosition: 'bodyClose' }` it would cause this issue. (Nuxt core is doing this)
