### ISSUE TITLE
fix: title template function breaks on hydration when object is spread

### ISSUE THREAD

**Issue by dargmuesli** [harlan-zw/nuxt-seo-kit#98]
### Describe the bug

When defining a `titleTemplate` as a function inside `useServerHead` **and spreading an object at the same time**, only the title is kept on client side hydration while the title separator and site name vanish:

```ts
useServerHead({
  title: 'ABC',
  ...{
    title: 'XYZ',
  }, // commenting this object out makes it work
  titleTemplate: (titleChunk) =>
    titleChunk && titleChunk !== siteConfig.name
      ? `${titleChunk} ${siteConfig.titleSeparator} ${siteConfig.name}`
      : siteConfig.name,
});
```

Using `useHead` works.

### Reproduction

https://stackblitz.com/edit/github-dpzmzy-pjbvws?file=app.vue

### System / Nuxt Info

```Shell
------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.7.1
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      modules
- Runtime Modules:  @nuxtseo/module@2.0.0-beta.25
- Build Modules:    -
------------------------------
```

**Comment by harlan-zw** [comment]
I'm not sure if I can replicate the spread issue. 

The underlying problem is that a function titleTemplate rendered `useServerHead` will never be hydratable so when it tries to set a title on the client side it clears the template.

A fix is to remove the function types for `useServerHead` and improve the docs  for title template.

**Comment by harlan-zw** [comment]
Have copied this to the Unhead repo as https://github.com/unjs/unhead/issues/221
